### ISSUE TITLE
Navigation to the page, which is already in the stack, doesn't silent pop the pages the in the middle.

### ISSUE THREAD

**Issue by bobbybonifacia** [exrin/Exrin#11]
Version 1.2.0
Having navigation stack A - B - C, when navigating from C to A, the B page is visible. According to this commit https://github.com/exrin/Exrin/commit/6c2c5b45cebae480e2ce87daffaefe91893b2f4e to the BaseStack, it should not happen.
Probably the problem is that instead of _viewsByKey _viewKeyTracking collection is used. Plus, when we have stack like A - B - C - D and would like to navigate from page D to page B, the first foreach loop will count all pages except B: A, C and D. But it should not pop page A.

**Comment by adamped** [comment]
@bobbybonifacia - this should now be fixed in 1.2.1. Please let me know and I will close the issue, if everything is successful.

**Comment by bobbybonifacia** [comment]
@adamped tried with 1.2.1: on Android the pages in the middle are still seen during the navigation. I created a sample app with 5 pages, so you can test it: https://github.com/bobbybonifacia/ExrinTestApp

**Comment by adamped** [comment]
Thanks @bobbybonifacia - just to let you know I am working on the reported issues. I use Exrin in all my production projects as well, so very invested in making sure they are all resolved. Just juggling many things at the moment.

**Comment by adamped** [comment]
@bobbybonifacia - Fixed and tested in Exrin 1.2.2. Please re-open if you continue to experience the issue.

**Comment by bobbybonifacia** [comment]
Works good when navigating in stack A - B - C - D - E to page A. But when I navigate to page B, the A page is shown and app freezes.
We are using Exrin version 1.2.2.

**Comment by adamped** [comment]
@bobbybonifacia - this has now been successfully reproduced and fixed in Exrin 1.2.3.

**Comment by bobbybonifacia** [comment]
@adamped  I installed the version 1.2.3 with NuGet package - bug is still there. But when I add Exrin as a project reference (downloaded the source code) - bug is fixed.

**Comment by adamped** [comment]
@bobbybonifacia - apologies, I packaged, without rebuilding in the correct config. 1.2.4 has been uploaded. 1.2.3 has been de-listed.
